### ISSUE TITLE
is.tibble deprecated

### ISSUE THREAD

**Issue by uschiLaa** [dicook/mulgar#3]
When using `hierfly` function we get a warning, should use is_tibble() instead of is.tibble()

**Comment by dicook** [comment]
Oh, that was a careless error. Should have been _ always. Feel free to make the change.Sent from my iPhoneOn 23 Jun 2023, at 5:31 pm, uschiLaa ***@***.***> wrote:﻿
When using hierfly function we get a warning, should use is_tibble() instead of is.tibble()
